# Generated by Django 4.1 on 2022-10-31 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0005_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='author',
        ),
    ]
