# Generated by Django 4.1 on 2022-11-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
