# Generated by Django 4.1 on 2022-11-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0009_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default='', upload_to='service_img')),
                ('image2', models.ImageField(default='', upload_to='service_img')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
