# Generated by Django 4.1 on 2022-11-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0011_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author',
            new_name='user',
        ),
    ]
