# Generated by Django 4.1 on 2022-11-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0012_rename_author_blogpost_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='user',
            new_name='author',
        ),
    ]
