# Generated by Django 4.1 on 2022-11-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0013_rename_user_blogpost_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author',
            new_name='user',
        ),
    ]
